apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  namespace: soboro
spec:
  replicas: 2
  selector:
    matchLabels: { app: frontend }
  template:
    metadata:
      labels: { app: frontend }
    spec:
      imagePullSecrets:
        - name: ecr-docker
      containers:
        - name: frontend
          image: frontend:latest
          ports: [{ containerPort: 3000 }]
          envFrom:
            - configMapRef: { name: frontend-env }
          readinessProbe:
            httpGet: { path: /, port: 3000 }
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /, port: 3000 }
            initialDelaySeconds: 30
            periodSeconds: 20
