apiVersion: v1
kind: Namespace
metadata: { name: argocd }
---
apiVersion: v1
kind: Namespace
metadata: { name: monitoring }
---
apiVersion: v1
kind: Namespace
metadata: { name: soboro } # 앱 배포용 네임스페이스
