apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns01
spec:
  acme:
    email: "<LE_EMAIL>" # 예: ops@example.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: le-account-key
    solvers:
      - dns01:
          route53:
            region: "<AWS_REGION>" # 예: ap-northeast-2
            hostedZoneID: "<HOSTED_ZONE_ID>"
            # 필요 시 역할 지정:
            # role: "arn:aws:iam::<AWS_ACCOUNT_ID>:role/<CERT_MANAGER_ROLE_NAME>"
